---
# base role handlers
- name: Update timezone data
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: ansible_os_family == "Debian"

- name: Generate locales
  command: locale-gen

- name: New aliases
  command: newaliases

# Ntp handlers
- name: Start ntp
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Restart ntp
  service:
    name: ntpd
    state: restarted
    enabled: yes

- name: Disable ntp
  service:
    name: ntpd
    state: stopped
    enabled: no

# Smartd handlers
- name: Restart smartd
  service:
    name: smartd
    state: restarted
    enabled: yes

# Ssh handlers
# Ubuntu names this services ssh
- name: Restart ssh
  service:
    name: ssh
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

# And Archlinux names it sshd
- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes
  when: ansible_os_family == "Archlinux"

- name: Restart ufw
  service:
    name: ufw
    state: restarted

# Chrony

- name: Restart chrony
  service:
    name: chrony
    state: restarted
    enabled: yes

- name: Start chrony
  service:
    name: chrony
    state: started
    enabled: yes

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
    enabled: yes

- name: Start chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

# Netplan
- name: Netplan generate
  command: netplan generate
  notify: Netplan apply
- name: Netplan apply
  command: netplan apply
